Feature/appointments UI
Konnen123/HealthcareManagement pull request #13
Opened 2024-12-01 22:30 UTC by Daniela0007

- am adaugat cele 4 componente, fiecare la o ruta diferita
- validari pentru create/update form
  (nu arata foarte appealing pana cand xdd)
- unit teste pentru 3 componente, code coverage minimul e pentru functii de 40 si ceva

2024-12-01 23:02 UTC, RazvanBoita commented
Cred ca e ok per total, dar cred ca ar trebui rezolvat ce zice sonarcloud, e cam mult 15%

2024-12-02 06:58 UTC, Konnen123 requested changes
In mare e ok, de vazut cu duplicated code si problemele aparute. Pentru partea duplicata, ar trebui facuta o componenta noua, care sa aiba toata logica de acolo pusa in ea.

2024-12-02 06:58 UTC, Konnen123 commented on healthcare-management/src/app/components/appointment-create/appointment-create.component.ts
> +      patientId: [
Aici ar trebui sa fie mutat in ngOnInit, nu trebuie lasat in constructor

2024-12-02 06:58 UTC, Konnen123 commented on healthcare-management/src/app/components/appointment-list/appointment-list.component.spec.ts
> +  //       id: '2',
De sters aici daca nu mai ai nevoie

2024-12-02 06:58 UTC, Konnen123 commented on healthcare-management/src/app/app-config/app.config.ts
> +import {environment} from '../../environments/environment.development';
Am uitat de mentionat, aici va trebui lasat import {environment} from '../../environments/environment'; deoarece acum vom avea doar un singur environment (poti sa redenumesti environment.development in environment). Am facut asta pentru deploy-ul pe vercel

2024-12-02 09:33 UTC, Konnen123 approved these changes

2024-12-02 10:10 UTC, merged